-- HR Recruitment Dashboard — Postgres schema
--
-- Mirrors the six Google Sheet tabs (Applications, Users, AuditLog,
-- Settings, Interviews, Assessments). Paste this into Supabase's
-- SQL Editor (Project -> SQL Editor -> New query) and run once.
--
-- All access is meant to go through Cloudflare Pages Functions using
-- the service_role key (same token-proxy shape as the current
-- functions/api/gas.ts) — never directly from the browser with the
-- anon key. RLS is enabled with no permissive policies as a
-- defense-in-depth backstop, not the primary access control.
--
-- Safe to re-run: the drops below clear both the Table-Editor names
-- (quoted, mixed case) and this file's own names. Only run this while
-- the tables are still empty — it destroys data by design.


-- =====================================================
-- DROP EXISTING
-- =====================================================
-- cascade clears the foreign keys pointing at Application.

drop table if exists "Assessment"  cascade;
drop table if exists "Assessments" cascade;
drop table if exists "Interviews"  cascade;
drop table if exists "AuditLog"    cascade;
drop table if exists "Setting"     cascade;
drop table if exists "Settings"    cascade;
drop table if exists "Users"       cascade;
drop table if exists "Application" cascade;
drop table if exists "Applications" cascade;

drop table if exists assessments  cascade;
drop table if exists interviews   cascade;
drop table if exists audit_log    cascade;
drop table if exists settings     cascade;
drop table if exists users        cascade;
drop table if exists applications cascade;


-- =====================================================
-- APPLICATIONS
-- =====================================================
-- application_id is the existing human-readable ID
-- ("APP-yyyyMMdd-XXXXXXXX") already embedded in resume filenames and
-- referenced by audit_log/interviews/assessments — kept as the
-- primary key instead of adding a redundant surrogate one.
--
-- available_date / expected_salary / experience stay TEXT rather than
-- DATE/NUMERIC: applicants type these freehand today (see the "1
-- month yrs exp" display quirk in the handoff notes), and a strict
-- type would reject or mangle real submissions. Revisit once the
-- public form itself gains real input constraints.
--
-- tags is a native array, replacing the Sheet's comma-joined string.

create table applications (
  application_id    text primary key,
  submitted_at      timestamptz not null default now(),

  full_name         text not null,
  ic_number         text,
  email             text not null
                    constraint applications_email_normalized
                    check (email = lower(btrim(email))),
  phone             text,
  address           text,
  city              text,
  state             text,
  postcode          text,

  position          text not null,
  available_date    text,
  expected_salary   text,
  experience        text,
  cover_message     text,

  resume_file_name  text,
  resume_url        text,

  preferred_state   text,
  preferred_branch  text not null,
  relocation        text,

  stage             text not null default 'Applied',
  rating            smallint not null default 0,
  tags              text[] not null default '{}',
  last_activity     timestamptz not null default now(),
  archived_at       timestamptz
);

-- Duplicate-check (7-day window) and Kanban board queries both filter
-- by these, same as the current Apps Script logic.
create index idx_applications_email on applications (email);
create index idx_applications_stage on applications (stage);
create index idx_applications_archived_at on applications (archived_at);
create index idx_applications_submitted_at on applications (submitted_at);


-- =====================================================
-- USERS
-- =====================================================
-- Admin and Senior Manager are global by role. For Area Manager,
-- Supervisor and Viewer, NULL/empty assignments mean no access.

create table users (
  email             text primary key
                    constraint users_email_normalized
                    check (email = lower(btrim(email))),
  name              text not null,
  role              text not null default 'Viewer',
  allowed_branches  text[],
  allowed_positions text[],
  active            boolean not null default true
);


-- =====================================================
-- AUDIT LOG
-- =====================================================
-- The Sheet stored "Name (email)" as one string; split here since a
-- real DB doesn't need to cram two fields into one for spreadsheet
-- readability.

create table audit_log (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz not null default now(),
  user_email        text,
  user_name         text,
  action            text not null,
  application_id    text references applications (application_id),
  remarks           text
);

create index idx_audit_log_application_id on audit_log (application_id);
create index idx_audit_log_created_at on audit_log (created_at);


-- =====================================================
-- SETTINGS
-- =====================================================
-- Category/Value/Active/Sort — drives Stage options,
-- AssessmentCriteria, RejectionReason, InterviewType,
-- ArchiveAfterDays, StaleAfterDays. Same shape as the Sheet tab.

create table settings (
  id                bigint generated by default as identity primary key,
  category          text not null,
  value             text not null,
  active            boolean not null default true,
  sort_order        int not null default 0
);

create index idx_settings_category on settings (category);


-- =====================================================
-- INTERVIEWS
-- =====================================================

create table interviews (
  id                bigint generated by default as identity primary key,
  application_id    text not null references applications (application_id),
  candidate_name    text,
  title             text not null default 'Interview',
  interviewer       text,
  interviewer_role  text,
  scheduled_at      timestamptz not null,
  duration_minutes  int not null default 45,
  type              text not null default 'Interview',
  status            text not null default 'Scheduled',
  meeting_link      text,
  created_by        text,
  created_at        timestamptz not null default now()
);

create index idx_interviews_application_id on interviews (application_id);


-- =====================================================
-- ASSESSMENTS
-- =====================================================
-- One row per criterion, same as the Sheet — grouped back into
-- scorecards (by assessor_email + assessed_at) in the API layer, same
-- grouping logic apiAssessments_ already does today.

create table assessments (
  id                bigint generated by default as identity primary key,
  application_id    text not null references applications (application_id),
  criterion         text not null,
  score             smallint not null default 0,
  comment           text,
  assessor          text,
  assessor_email    text,
  assessed_at       timestamptz not null default now()
);

create index idx_assessments_application_id on assessments (application_id);


-- =====================================================
-- ROW LEVEL SECURITY — defense in depth, not primary access control
-- =====================================================
-- No policies are added, so RLS denies everything by default. The
-- Cloudflare Pages Functions layer uses the service_role key, which
-- bypasses RLS entirely — this only matters if the anon key or a
-- browser ever ends up talking to Supabase directly, which the
-- architecture doesn't do.

alter table applications enable row level security;
alter table users        enable row level security;
alter table audit_log    enable row level security;
alter table settings     enable row level security;
alter table interviews   enable row level security;
alter table assessments  enable row level security;


-- =====================================================
-- RESUME STORAGE
-- =====================================================
-- Private bucket — public = false means no anonymous read, even with
-- the direct object URL. functions/api/submit.ts uploads with the
-- service_role key (bypasses RLS same as the tables above), and
-- functions/api/data.ts generates a short-lived signed URL each time
-- the applicant drawer actually opens a resume, rather than storing a
-- link that would go dead when it expires.

insert into storage.buckets (id, name, public)
values ('resumes', 'resumes', false)
on conflict (id) do nothing;
